/*
 * ════════════════════════════════════════════════════════════════
 *   SILVER & SALT CAPITAL — NETWORK ECOSYSTEM GRAPH
 * ════════════════════════════════════════════════════════════════
 *
 *   ONE tagged graph spanning both communities:
 *     • "monarch"      — the broader startup / investing world (Monarch PBC)
 *     • "silver-salt"  — the local Utah Silver & Salt Capital community
 *   A person can belong to BOTH (the bridge-builders matter most).
 *
 *   ── HOW TO ADD A PERSON ──
 *   Copy a block below and fill it in. Refresh ecosystem.html to see them.
 *   (Phase 2 adds a phone-friendly capture form so you never hand-edit this.)
 *
 *   ── FIELD GUIDE ──
 *   id           unique slug, e.g. "jane-doe"
 *   name         full name
 *   communities  ["monarch"] | ["silver-salt"] | ["monarch","silver-salt"]
 *   status       "connected" (you've met) | "prospect" (researched, not yet met)
 *   role, org    title and organization
 *   location     "City, ST"
 *   linkedin, email
 *   metWhere, metDate    where/when you first connected (connected only)
 *   skills       tags from SKILLS below — what they can help with (reach out)
 *   interests    tags from INTERESTS below — common ground (connect)
 *   connections  array of other people's ids — who they know (the graph edges)
 *   health       "thriving" | "warm" | "cooling" | "dormant"  (relationship temp)
 *   lastTouch    "YYYY-MM-DD" of last meaningful contact
 *   notes        free text — context for your future self
 *
 *   Keep skills/interests drawn from the vocab so filters stay clean.
 *   Add new tags to the vocab when you genuinely need them.
 */

// ── CONTROLLED VOCABULARY (extend as needed) ──
const SKILLS = [
  "fundraising", "angel-investing", "venture-capital", "fund-management",
  "fintech", "legal", "accounting", "operations", "marketing", "design",
  "engineering", "recruiting", "sales", "public-relations", "policy",
  "education", "community-building", "deal-sourcing", "due-diligence",
];

const INTERESTS = [
  "women-in-vc", "gender-equity", "climate", "impact-investing",
  "local-economies", "health-wellness", "consumer", "life-sciences",
  "future-of-work", "education", "utah-startups", "outdoors",
];


const PEOPLE = [
  // ─── SILVER & SALT CAPITAL (Utah) ───
  {
    id: "tori-horton",
    name: "Tori Horton",
    communities: ["silver-salt", "monarch"], status: "connected",
    role: "Founder", org: "Silver & Salt Capital",
    location: "Utah",
    linkedin: "https://linkedin.com/in/4torihorton", email: "",
    metWhere: "", metDate: "",
    skills: ["fund-management", "community-building", "fundraising"],
    interests: ["women-in-vc", "utah-startups", "impact-investing"],
    connections: [],
    health: "thriving", lastTouch: "",
    notes: "You. The hub of the graph.",
  },

  // ─── MONARCH ECOSYSTEM — prospects from research corpus ───
  // (researched leaders in the women's investing world; not yet personally met)
  {
    id: "katherine-jollon-colsher",
    name: "Katherine Jollon Colsher",
    communities: ["monarch"], status: "prospect",
    role: "President & CEO", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/katherine-jollon-colsher", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "seema-hingorani",
    name: "Seema Hingorani",
    communities: ["monarch"], status: "prospect",
    role: "Founder & Board Chair", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/seema-hingorani-6156b85", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "janine-firpo",
    name: "Janine Firpo",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder", org: "",
    location: "Oakland, CA",
    linkedin: "https://linkedin.com/in/janine-firpo-047282", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "ellen-remmer",
    name: "Ellen Remmer",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder", org: "",
    location: "Boston, MA",
    linkedin: "https://linkedin.com/in/ellen-remmer-8503762", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "angela-lee",
    name: "Angela Lee",
    communities: ["monarch"], status: "prospect",
    role: "Founder & CEO", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/hiangela", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "jill-johnson",
    name: "Jill Johnson",
    communities: ["monarch"], status: "prospect",
    role: "CEO", org: "",
    location: "Newark, NJ",
    linkedin: "https://linkedin.com/in/smallbizexpert", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "natalia-oberti-noguera",
    name: "Natalia Oberti Noguera",
    communities: ["monarch"], status: "prospect",
    role: "Founder", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/nataliaobertinoguera", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "gwen-edwards",
    name: "Gwen Edwards",
    communities: ["monarch"], status: "prospect",
    role: "Chair & Lead Instructor", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/gwencedwards", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "susan-preston",
    name: "Susan Preston",
    communities: ["monarch"], status: "prospect",
    role: "Trustee & Lead Instructor", org: "",
    location: "Seattle, WA",
    linkedin: "https://linkedin.com/in/susanpreston", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "katherine-hague",
    name: "Katherine Hague",
    communities: ["monarch"], status: "prospect",
    role: "Founder", org: "",
    location: "Toronto, ON (Canada)",
    linkedin: "", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "eleni-aktypi",
    name: "Eleni Aktypi",
    communities: ["monarch"], status: "prospect",
    role: "Managing Director (linkedin.com/in/elenidaktypi) Athens, Greece", org: "",
    location: "",
    linkedin: "", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "loretta-mccarthy",
    name: "Loretta McCarthy",
    communities: ["monarch"], status: "prospect",
    role: "Co-CEO & Managing Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/loretta-mccarthy-b885a", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "jo-ann-corkran",
    name: "Jo Ann Corkran",
    communities: ["monarch"], status: "prospect",
    role: "Co-CEO & Managing Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/jo-ann-corkran-06600531", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "jenny-abramson",
    name: "Jenny Abramson",
    communities: ["monarch"], status: "prospect",
    role: "Founder & Managing Partner", org: "",
    location: "Washington, DC",
    linkedin: "https://linkedin.com/in/jenny-abramson-bb75297", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "heidi-krauel-patel",
    name: "Heidi Krauel Patel",
    communities: ["monarch"], status: "prospect",
    role: "Managing Partner", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/heidi-krauel-patel-a4b5", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "anu-duggal",
    name: "Anu Duggal",
    communities: ["monarch"], status: "prospect",
    role: "Founding Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/anu-duggal-568222", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "aileen-lee",
    name: "Aileen Lee",
    communities: ["monarch"], status: "prospect",
    role: "Founder & Managing Partner", org: "",
    location: "Palo Alto, CA",
    linkedin: "https://linkedin.com/in/aileenwlee", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "caroline-duffy",
    name: "Caroline Duffy",
    communities: ["monarch"], status: "prospect",
    role: "Partner", org: "",
    location: "Palo Alto, CA",
    linkedin: "https://linkedin.com/in/caroline-duffy-vc", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "karen-cahn",
    name: "Karen Cahn",
    communities: ["monarch"], status: "prospect",
    role: "Founder & CEO", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/karen-cahn", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "desiree-vargas-wrigley",
    name: "Desiree Vargas Wrigley",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder", org: "",
    location: "Chicago, IL",
    linkedin: "https://linkedin.com/in/desireevw", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "sharon-vosmek",
    name: "Sharon Vosmek",
    communities: ["monarch"], status: "prospect",
    role: "CEO & Managing Partner", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/sharonvosmek", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "victoria-pettibone",
    name: "Victoria Pettibone",
    communities: ["monarch"], status: "prospect",
    role: "CIO & Managing Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/victoriapettibone", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "elizabeth-yin",
    name: "Elizabeth Yin",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & GP", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/elizabethyin", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "eric-bahn",
    name: "Eric Bahn",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & GP", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/ericbahn", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "trish-costello",
    name: "Trish Costello",
    communities: ["monarch"], status: "prospect",
    role: "Founder & CEO", org: "",
    location: "San Mateo, CA",
    linkedin: "https://linkedin.com/in/trishcostello1", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "alicia-robb",
    name: "Alicia Robb",
    communities: ["monarch"], status: "prospect",
    role: "Founder & CEO", org: "",
    location: "Kanab, UT",
    linkedin: "https://linkedin.com/in/alicia-robb-a888228", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "lindsey-taylor-wood",
    name: "Lindsey Taylor Wood",
    communities: ["monarch"], status: "prospect",
    role: "Founder & GP", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/lindseytaylorwood", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "olivia-fleming",
    name: "Olivia Fleming",
    communities: ["monarch"], status: "prospect",
    role: "Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/olivia-fleming-88186b46", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "julie-castro-abrams",
    name: "Julie Castro Abrams",
    communities: ["monarch"], status: "prospect",
    role: "Managing Partner", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/julie-castro-abrams", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "serena-williams",
    name: "Serena Williams",
    communities: ["monarch"], status: "prospect",
    role: "Founder", org: "",
    location: "Palm Beach Gardens, FL",
    linkedin: "https://linkedin.com/in/serena-williams-99612b205", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "beth-ferreira",
    name: "Beth Ferreira",
    communities: ["monarch"], status: "prospect",
    role: "General Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/bethmferreira", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "mallun-yen",
    name: "Mallun Yen",
    communities: ["monarch"], status: "prospect",
    role: "Founder & Managing Partner", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/mallun", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "dana-marohn-spiliotis",
    name: "Dana Marohn Spiliotis",
    communities: ["monarch"], status: "prospect",
    role: "Partner", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/danamarohn", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "pocket-sun",
    name: "Pocket Sun",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & Managing Partner", org: "",
    location: "Vancouver, BC",
    linkedin: "https://linkedin.com/in/pocketsun", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "elizabeth-galbut",
    name: "Elizabeth Galbut",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & Managing Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/egalbut", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "jennifer-neundorfer",
    name: "Jennifer Neundorfer",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & MP", org: "",
    location: "Boston, MA",
    linkedin: "https://linkedin.com/in/jkneundorfer", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "maren-thomas-bannon",
    name: "Maren Thomas Bannon",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & MP", org: "",
    location: "London, UK",
    linkedin: "https://linkedin.com/in/marenbannon", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "linnea-roberts",
    name: "Linnea Roberts",
    communities: ["monarch"], status: "prospect",
    role: "Founder & CEO", org: "",
    location: "Atherton, CA",
    linkedin: "https://linkedin.com/in/linnea-roberts-5a3630292", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "ita-ekpoudom",
    name: "Ita Ekpoudom",
    communities: ["monarch"], status: "prospect",
    role: "Partner", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/itaekpoudom", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "arlan-hamilton",
    name: "Arlan Hamilton",
    communities: ["monarch"], status: "prospect",
    role: "Founder & Managing Partner", org: "",
    location: "Los Angeles, CA",
    linkedin: "https://linkedin.com/in/arlanhamilton", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "christie-pitts",
    name: "Christie Pitts",
    communities: ["monarch"], status: "prospect",
    role: "General Partner", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/christiepitts", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "elisa-miller-out",
    name: "Elisa Miller-Out",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & MP", org: "",
    location: "Ithaca, NY",
    linkedin: "https://linkedin.com/in/elisamillerout", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "heather-henyon",
    name: "Heather Henyon",
    communities: ["monarch"], status: "prospect",
    role: "Founding GP (linkedin.com/in/heatherhenyon) Dubai/New York", org: "",
    location: "",
    linkedin: "", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "edith-dorsen",
    name: "Edith Dorsen",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & MD", org: "",
    location: "Portland, OR",
    linkedin: "https://linkedin.com/in/edithdorsen", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "monica-dodi",
    name: "Monica Dodi",
    communities: ["monarch"], status: "prospect",
    role: "Co-Founder & MD", org: "",
    location: "Los Angeles, CA",
    linkedin: "https://linkedin.com/in/monicadodi", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "laura-rippy",
    name: "Laura Rippy",
    communities: ["monarch"], status: "prospect",
    role: "Managing Partner", org: "",
    location: "Boston, MA",
    linkedin: "https://linkedin.com/in/laurarippy", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "meera-oak",
    name: "Meera Oak",
    communities: ["monarch"], status: "prospect",
    role: "Partner", org: "",
    location: "San Francisco, CA",
    linkedin: "https://linkedin.com/in/meeraoak", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
  {
    id: "patricia-lizarraga",
    name: "Patricia Lizarraga",
    communities: ["monarch"], status: "prospect",
    role: "Managing Partner & Founder", org: "",
    location: "New York, NY",
    linkedin: "https://linkedin.com/in/patricializarraga", email: "",
    metWhere: "", metDate: "",
    skills: [],
    interests: [],
    connections: [],
    health: "", lastTouch: "",
    notes: "",
  },
];

// Expose for both module and plain-script use
if (typeof module !== 'undefined') { module.exports = { PEOPLE, SKILLS, INTERESTS }; }
